### ISSUE TITLE
How can I jest.mock useDeepCompareCallback hook

### ISSUE THREAD

**Issue by guiananias** [sandiiarov/use-deep-compare#169]
I have a custom hook that return an object with an inside function that use the `useDeepCompareCallback`, someone know how can I mock `use-deep-compare` to make a efficiently unit test? 

The custom hook example is like this:
```js
import { useDeepCompareCallback } from 'use-deep-compare';

const useCustomHook = () => {
  // some more functions...
  const memoizedFunction = useDeepCompareCallback(() => {
    // some logic...
  }, []);

  return {
    // other returned functions...
    memoizedFunction,
  }
}

export default useCustomHook;
```

On my `test.js` file, I'm trying to use `jest.mock('use-deep-compare')`, but I can't get a right value returned by my memoized function.

**Comment by sandiiarov** [comment]
I believe you can do something like that:

```typescript
const mockedUseDeepCompareCallback = jest.fn();

jest.mock('use-deep-compare', () => ({
  useDeepCompareCallback: () => mockedUseDeepCompareCallback(),
}));
```

**Comment by guiananias** [comment]
@sandiiarov It's works to me. Thanks! :heart:
