### ISSUE TITLE
What about useDeepCompareState?

### ISSUE THREAD

**Issue by sudhanshu16** [sandiiarov/use-deep-compare#188]
I was thinking this hook will be a good fit for this package.
I assume it might have come to your mind, why didn't you decide to add it? If it didn't then let's consider it.

Example for what I mean:
```ts
const [object, setObject] = useState<Record<string, string>>({ a: 1 })
const [deepObject, setDeepObject] = useDeepCompareState<Record<string, string>>({ a: 1 })
```

if you run `setObject({ a: 1 })` any number of times, then react will rerender the component.
But if you run `setDeepObject({ a: 1 })` any number of times, then the component should not rerender.

this is basically a utility for usecases where we see something like this:
```ts
if (object !== newObject) setObject(newObject)
```
which can be simplified to:
```ts
setDeepObject(newObject)
```
and this wont do unnecessary rerenders.

It is particularly helpful in `useEffect` which set state, if there is no `if` check then they result in infinite loop (`Maximum update depth exceeded` error)

Let me know what you think about this! Thanks for the awesome package

**Comment by sandiiarov** [comment]
Thanks for the suggestion! I didn't think about it.

Usually I wrap setState function into the useEffect hook to avoid unnecessary calls.

In your example setDeepObject function will be called as many times as any prop or state has changed. It will be expensive b/c it will run compare function.

That's how I do this:

```JavaScript
const [state, setState] = useState({ a: 1 });

useDeepcompareEffect(() => {
  ...
  setState(newState);
}, [newState]);
```

You can put any logic into that hook and compare new state only once.
