### ISSUE TITLE
ESBuild Failed

### ISSUE THREAD

**Issue by hendra-foo** [sandiiarov/use-deep-compare#254]
I'm running @udecode/plate which have deps on this package, and found issue when running my app
<img width="1007" alt="image" src="https://github.com/sandiiarov/use-deep-compare/assets/28421317/92a02329-38c4-40c7-86de-158bcbfb42ca">

looks like the issue is `"module": "dist-web/index.js"` not found.
<img width="303" alt="image" src="https://github.com/sandiiarov/use-deep-compare/assets/28421317/70279e48-54f4-4dfd-96e6-e87b181030fb">

changing the line to `"module": "dist-node/index.js"` fixed the issue

**Comment by keysinandy** [comment]
It looks like /dist-web /dist-src dist-types not publish
![image](https://github.com/sandiiarov/use-deep-compare/assets/27417016/d83e8ac3-333b-49e0-a198-e758ffb46032)

**Comment by RJWadley** [comment]
Also having issues with this because the types aren't published either, downgrading to version 1.1.0 helped

**Comment by sandiiarov** [comment]
It looks like `npm publish` is not reading blob patterns anymore in `package.json` file and I had to explicitly set all folders which have to be included into the tarball contents.

```diff
// package.json

   "files": [
-    "dist-*/",
+    "dist-node/",
+    "dist-src/",
+    "dist-types/",
+    "dist-web/",
     "bin/"
   ],
```

I pushed `v1.2.1` with the fix

**Comment by mbrevda** [comment]
> I pushed v1.2.1 with the fix

seems to have fixed the issue, thanks!
