### ISSUE TITLE
isPrimitive error

### ISSUE THREAD

**Issue by pmoskvin** [sandiiarov/use-deep-compare#48]
I get an error if I pass in a dependency something like [a, b], where a is null or object, b is primitive

**Comment by sandiiarov** [comment]
I guess this is the right behavior. You don't need to use `useDeepCompare` hook for that case. Just use the standard one.

**Comment by pmoskvin** [comment]
There is no need, as I am going to pass an object with deep nesting... or null.

**Comment by aigoncharov** [comment]
@sandiiarov what if I want to depend on an object which could also be null? For the object I want to have a deep equality comparison, but I get the exception if this object is nullable.

**Comment by matthias-ccri** [comment]
Can this be fixed? I frequently use states that switch between being objects and undefined. I don't think the error is appropriate.
